# Generated by Django 5.2.7 on 2025-10-09 12:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_group_options_enrollment_lessons_attended_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма')),
                ('months_count', models.PositiveIntegerField(default=1, verbose_name='Количество месяцев')),
                ('notes', models.TextField(blank=True, verbose_name='Примечания')),
                ('payment_month', models.DateField(help_text='Первый день месяца, за который вносится оплата', verbose_name='Месяц оплаты')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='groups.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('student', 'group', 'payment_month')},
            },
        ),
        migrations.CreateModel(
            name='PaymentDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата оплаты')),
                ('month_number', models.PositiveIntegerField(verbose_name='Номер месяца')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Оплачено')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_dates', to='groups.group', verbose_name='Группа')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_dates', to='students.student', verbose_name='Ученик')),
            ],
            options={
                'verbose_name': 'Дата оплаты',
                'verbose_name_plural': 'Даты оплат',
                'unique_together': {('student', 'group', 'month_number')},
            },
        ),
    ]
