# Generated by Django 5.2.7 on 2025-10-13 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='payment',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='payment',
            name='months_count',
        ),
    ]
