# Generated by Django 5.2.7 on 2025-10-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='payment_month',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_month_number',
            field=models.PositiveIntegerField(default=10, help_text='Номер месяца (1, 2, 3...), за который вносится оплата', verbose_name='Номер месяца оплаты'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentdate',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплаченная сумма'),
        ),
        migrations.AddField(
            model_name='paymentdate',
            name='required_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Требуемая сумма'),
        ),
    ]
