# Generated by Django 5.2.7 on 2025-10-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.AddField(
            model_name='student',
            name='phone_parent',
            field=models.CharField(blank=True, verbose_name='номер родителей'),
        ),
    ]
