# Generated by Django 5.2.7 on 2025-10-09 12:16

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-start_date', 'name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AddField(
            model_name='enrollment',
            name='lessons_attended',
            field=models.PositiveIntegerField(default=0, verbose_name='Посещенных занятий'),
        ),
        migrations.AddField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активная группа'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество проведенных занятий'),
        ),
        migrations.AddField(
            model_name='group',
            name='lessons_per_month',
            field=models.PositiveIntegerField(default=15, verbose_name='Занятий в месяце'),
        ),
        migrations.AddField(
            model_name='group',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость обучения в месяц'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enrolled_from',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата зачисления'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='group',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Дата начала 1-го месяца обучения'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'group')},
        ),
    ]
