# Generated by Django 5.2.7 on 2025-10-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_group_options_enrollment_lessons_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='lessons_count',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='start_lesson',
            field=models.PositiveIntegerField(default=1, verbose_name='Начальное занятие'),
        ),
    ]
