# Generated by Django 5.2.7 on 2025-11-03 14:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_remove_group_lessons_count_enrollment_start_lesson'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marked_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Когда отмечено')),
                ('source', models.CharField(choices=[('single', 'Индивидуально (кнопка у студента)'), ('bulk', 'Групповое (кнопка «занятие для всех»)')], default='single', max_length=12, verbose_name='Источник отметки')),
                ('lesson_no_at_time', models.PositiveIntegerField(default=0, verbose_name='Номер занятия у студента на момент отметки')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='groups.enrollment', verbose_name='Запись зачисления')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='groups.group', verbose_name='Группа')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_marked', to=settings.AUTH_USER_MODEL, verbose_name='Кто отметил')),
            ],
            options={
                'verbose_name': 'Лог посещаемости',
                'verbose_name_plural': 'Логи посещаемости',
                'ordering': ['-marked_at'],
                'indexes': [models.Index(fields=['group', '-marked_at'], name='groups_atte_group_i_eb990c_idx'), models.Index(fields=['enrollment', '-marked_at'], name='groups_atte_enrollm_ee763b_idx')],
            },
        ),
    ]
