# Generated by Django 5.2.7 on 2025-10-19 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название отчета')),
                ('report_type', models.CharField(choices=[('daily', 'Ежедневный'), ('weekly', 'Еженедельный'), ('monthly', 'Ежемесячный'), ('custom', 'Произвольный период')], max_length=10, verbose_name='Тип отчета')),
                ('start_date', models.DateField(verbose_name='Начальная дата')),
                ('end_date', models.DateField(verbose_name='Конечная дата')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общий доход')),
                ('total_debt', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Общая задолженность')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Финансовый отчет',
                'verbose_name_plural': 'Финансовые отчеты',
                'ordering': ['-created_at'],
            },
        ),
    ]
